# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'learn4SDWebImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for learn4SDWebImage
  pod 'SDWebImage', '~> 4.0'

  target 'learn4SDWebImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'learn4SDWebImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
